import { Dimensions } from 'react-native';

const SCREEN_HEIGHT = Dimensions.get('window').height;
const SCREEN_WIDTH = Dimensions.get('window').width;

export const PREORDER_LAYOUT = {
  // Bottom Sheet
  SHEET_HEIGHT: SCREEN_HEIGHT * 0.9,
  SHEET_WIDTH: SCREEN_WIDTH,
  SHEET_BORDER_RADIUS: 20,
  SHEET_HANDLE_WIDTH: 40,
  SHEET_HANDLE_HEIGHT: 4,
  
  // Header
  HEADER_PADDING_HORIZONTAL: 15,
  HEADER_TITLE_FONT_SIZE: 18,
  HEADER_BUTTON_SIZE: 44,
  HEADER_BUTTON_FONT_SIZE: 16,
  HEADER_HEIGHT: 60,
  
  SECTION_MARGIN_TOP: 20,
  SECTION_PADDING_HORIZONTAL: 15,
  SECTION_PADDING_VERTICAL: 10,
  SECTION_GAP: 16,
  
  PRODUCT_ITEM_HEIGHT: 80,
  PRODUCT_ITEM_PADDING: 16,
  PRODUCT_QUANTITY_SIZE: 36,
  PRODUCT_QUANTITY_FONT_SIZE: 16,
  PRODUCT_NAME_FONT_SIZE: 16,
  PRODUCT_SIZE_FONT_SIZE: 13,
  PRODUCT_PRICE_FONT_SIZE: 18,
  PRODUCT_SWIPE_ACTIONS_WIDTH: 150,
  PRODUCT_SWIPE_BUTTON_WIDTH: 75,
  
  // Order Type
  ORDER_TYPE_HEIGHT: 'auto',
  ORDER_TYPE_BORDER_RADIUS: 12,
  ORDER_TYPE_PADDING: 16,
  ORDER_TYPE_ICON_SIZE: 24,
  ORDER_TYPE_LABEL_FONT_SIZE: 14,
  ORDER_TYPE_VALUE_FONT_SIZE: 16,
  
  // Modal
  MODAL_OVERLAY_OPACITY: 0.5,
  MODAL_HEIGHT_PERCENTAGE: 0.6,
  MODAL_BORDER_RADIUS: 20,
  MODAL_HEADER_HEIGHT: 60,
  MODAL_OPTION_HEIGHT: 68,
  MODAL_OPTION_PADDING: 16,
  
  // Total Price
  TOTAL_ROW_HEIGHT: 44,
  TOTAL_LABEL_FONT_SIZE: 14,
  TOTAL_VALUE_FONT_SIZE: 16,
  TOTAL_FINAL_LABEL_FONT_SIZE: 16,
  TOTAL_FINAL_VALUE_FONT_SIZE: 16,
  DIVIDER_HEIGHT: 1,
  
  // Footer
  FOOTER_HEIGHT: 90,
  FOOTER_PADDING: 20,
  FOOTER_BUTTON_HEIGHT: 56,
  FOOTER_BUTTON_BORDER_RADIUS: 16,
  FOOTER_INFO_FONT_SIZE: 14,
  FOOTER_BUTTON_TEXT_SIZE: 18,
  
  // Animation
  SPRING_DAMPING: 20,
  SPRING_STIFFNESS: 200,
  FADE_DURATION: 200,
  SLIDE_DURATION: 300,
};