export const WELCOME_LAYOUT = {
  // Header
  HEADER_PADDING_HORIZONTAL: 16,
  HEADER_PADDING_VERTICAL: 12,
  HEADER_BORDER_BOTTOM_WIDTH: 1,
  HEADER_ICON_SIZE: 40,
  HEADER_ICON_BORDER_RADIUS: 20,
  
  // Greeting
  GREETING_ICON_SIZE: 24,
  GREETING_TEXT_SIZE: 18,
  GREETING_GAP: 8,
  
  // Section
  SECTION_PADDING_HORIZONTAL: 16,
  SECTION_MARGIN_BOTTOM: 24,
  SECTION_TITLE_SIZE: 20,
  SECTION_TITLE_MARGIN_BOTTOM: 16,
  
  // Card
  CARD_BORDER_RADIUS: 16,
  CARD_PADDING: 20,
  CARD_SHADOW_RADIUS: 8,
  CARD_ELEVATION: 5,
  CARD_MARGIN_TOP: 16,
  CARD_SHADOW_OPACITY: 0.1,
  CARD_SHADOW_OFFSET_HEIGHT: 2,
  CARD_SHADOW_OFFSET_WIDTH: 0,
  
  // Login card
  LOGIN_TITLE_SIZE: 24,
  LOGIN_TITLE_MARGIN_BOTTOM: 8,
  LOGIN_SUBTITLE_SIZE: 14,
  LOGIN_SUBTITLE_LINE_HEIGHT: 20,
  LOGIN_SUBTITLE_MARGIN_BOTTOM: 16,
  LOGIN_BUTTON_BORDER_RADIUS: 24,
  LOGIN_BUTTON_PADDING_VERTICAL: 14,
  LOGIN_BUTTON_MARGIN_BOTTOM: 16,
  LOGIN_BUTTON_TEXT_SIZE: 16,
  LOGIN_BUTTON_ARROW_SIZE: 24,
  
  // Brand selector
  BRAND_CARD_SIZE: 80,
  BRAND_CARD_BORDER_RADIUS: 12,
  BRAND_SCROLL_GAP: 12,
  BRAND_TEXT_SIZE: 14,
  BRAND_CARD_PADDING: 16,
  
  // Quick actions
  QUICK_ACTION_ICON_SIZE: 60,
  QUICK_ACTION_ICON_BORDER_RADIUS: 30,
  QUICK_ACTION_GAP: 8,
  QUICK_ACTION_LABEL_SIZE: 12,
  
  // Promo banner
  PROMO_BANNER_MIN_HEIGHT: 120,
  PROMO_BANNER_BORDER_RADIUS: 16,
  PROMO_BANNER_PADDING: 20,
  PROMO_BANNER_GAP: 8,
  PROMO_BANNER_TITLE_SIZE: 18,
  PROMO_BANNER_SUBTITLE_SIZE: 14,
  PROMO_BANNER_SUBTITLE_LINE_HEIGHT: 20,
  PROMO_DOT_SIZE: 8,
  PROMO_DOT_ACTIVE_WIDTH: 24,
  PROMO_DOT_BORDER_RADIUS: 4,
  PROMO_DOT_GAP: 8,
  PROMO_DOT_MARGIN_TOP: 12,
  
  // Product card
  PRODUCT_CARD_WIDTH_PERCENTAGE: 0.48,
  PRODUCT_CARD_BORDER_RADIUS: 12,
  PRODUCT_CARD_MARGIN_BOTTOM: 16,
  PRODUCT_CARD_INFO_PADDING: 12,
  PRODUCT_IMAGE_ASPECT_RATIO: 1,
  PRODUCT_BADGE_TOP: 8,
  PRODUCT_BADGE_LEFT: 8,
  PRODUCT_BADGE_RIGHT: 8,
  PRODUCT_BADGE_BORDER_RADIUS: 16,
  PRODUCT_BADGE_PADDING_HORIZONTAL: 12,
  PRODUCT_BADGE_PADDING_VERTICAL: 4,
  PRODUCT_BADGE_TEXT_SIZE: 11,
  PRODUCT_DISCOUNT_BADGE_BORDER_RADIUS: 12,
  PRODUCT_DISCOUNT_BADGE_PADDING_HORIZONTAL: 8,
  PRODUCT_DISCOUNT_BADGE_PADDING_VERTICAL: 4,
  PRODUCT_NAME_SIZE: 14,
  PRODUCT_NAME_MARGIN_BOTTOM: 8,
  PRODUCT_NAME_MIN_HEIGHT: 40,
  PRODUCT_PRICE_SIZE: 16,
  PRODUCT_ORIGINAL_PRICE_SIZE: 12,
  PRODUCT_ORIGINAL_PRICE_MARGIN_TOP: 2,
  PRODUCT_ADD_BUTTON_SIZE: 32,
  PRODUCT_ADD_BUTTON_BORDER_RADIUS: 16,
  PRODUCT_ADD_ICON_SIZE: 20,
  
  // Category scroll
  CATEGORY_ITEM_WIDTH: 80,
  CATEGORY_ICON_SIZE: 60,
  CATEGORY_ICON_BORDER_RADIUS: 32,
  CATEGORY_ICON_MARGIN_BOTTOM: 8,
  CATEGORY_SCROLL_GAP: 16,
  CATEGORY_LABEL_SIZE: 11,
  CATEGORY_ICON_EMOJI_SIZE: 24,

  LOYALTY_TEXT_PADDING_VERTICAL: 8,
  LOYALTY_TEXT_FONT_SIZE: 14,
}