export const LOGIN_LAYOUT = {
  // Hero section
  HERO_HEIGHT: 280,
  
  // Close button
  CLOSE_BUTTON_SIZE: 40,
  CLOSE_BUTTON_TOP: 16,
  CLOSE_BUTTON_RIGHT: 16,
  CLOSE_BUTTON_BORDER_RADIUS: 20,
  
  // Form container
  FORM_PADDING_HORIZONTAL: 24,
  FORM_PADDING_TOP: 32,
  
  // Input
  INPUT_BORDER_RADIUS: 12,
  INPUT_PADDING_HORIZONTAL: 16,
  INPUT_PADDING_VERTICAL: 14,
  INPUT_GAP: 12,
  INPUT_BORDER_WIDTH: 1,
  
  // Button
  BUTTON_BORDER_RADIUS: 12,
  BUTTON_PADDING_VERTICAL: 16,
  BUTTON_MARGIN_TOP: 16,
  
  // Spacing
  BRAND_NAME_MARGIN_BOTTOM: 20,
  WELCOME_TEXT_MARGIN_BOTTOM: 8,
  DIVIDER_MARGIN_VERTICAL: 20,
  SOCIAL_BUTTON_MARGIN_BOTTOM: 12,
  SOCIAL_BUTTON_GAP: 12,
  
  // Font sizes
  CLOSE_BUTTON_FONT_SIZE: 24,
  HERO_FONT_SIZE: 16,
  WELCOME_FONT_SIZE: 16,
  BRAND_NAME_FONT_SIZE: 28,
  PHONE_INPUT_FONT_SIZE: 14,
  BUTTON_FONT_SIZE: 14,
  DIVIDER_FONT_SIZE: 12,
  FLAG_EMOJI_FONT_SIZE: 14,
  SOCIAL_ICON_FONT_SIZE: 18,
  
  // Brand name letter spacing
  BRAND_NAME_LETTER_SPACING: 1,
  
  // Timing
  KEYBOARD_FOCUS_DELAY: 400, // ms after modal animation completes
}