export const LOGIN_LAYOUT = {
  // Hero section
  HERO_HEIGHT: 280,
  HERO_FONT_SIZE: 16,
  
  // Close button
  CLOSE_BUTTON_SIZE: 40,
  CLOSE_BUTTON_TOP: 16,
  CLOSE_BUTTON_RIGHT: 16,
  CLOSE_BUTTON_BORDER_RADIUS: 20,
  CLOSE_BUTTON_FONT_SIZE: 14,
  
  // Form container
  FORM_PADDING_HORIZONTAL: 24,
  FORM_PADDING_TOP: 32,
  
  // Welcome text
  WELCOME_FONT_SIZE: 16,
  WELCOME_TEXT_MARGIN_BOTTOM: 8,
  
  // Brand name
  BRAND_NAME_FONT_SIZE: 28,
  BRAND_NAME_MARGIN_BOTTOM: 20,
  BRAND_NAME_LETTER_SPACING: 1,
  
  // Input
  INPUT_BORDER_RADIUS: 12,
  INPUT_PADDING_HORIZONTAL: 16,
  INPUT_PADDING_VERTICAL: 14,
  INPUT_GAP: 12,
  INPUT_BORDER_WIDTH: 1,
  INPUT_BUTTON_GAP: 16,
  
  // Button
  BUTTON_BORDER_RADIUS: 12,
  BUTTON_PADDING_VERTICAL: 16,
  
  // Divider
  DIVIDER_FONT_SIZE: 12,
  DIVIDER_MARGIN_VERTICAL: 20,
  
  // Timing
  KEYBOARD_FOCUS_DELAY: 400,
  OTP_SENDING_DURATION: 2000,
}