export const ORDER_LAYOUT = {
  // Header
  HEADER_PADDING_HORIZONTAL: 16,
  HEADER_PADDING_VERTICAL: 12,
  HEADER_ICON_SIZE: 24,
  HEADER_TITLE_SIZE: 20,
  
  // Category Scroll
  CATEGORY_ITEM_WIDTH: 80,
  CATEGORY_ICON_SIZE: 60,
  CATEGORY_LABEL_SIZE: 12,
  CATEGORY_SCROLL_GAP: 16,
  CATEGORY_SCROLL_PADDING: 16,
  
  // Promo Section
  PROMO_SECTION_PADDING: 16,
  PROMO_TITLE_SIZE: 24,
  PROMO_COUNTDOWN_SIZE: 14,
  PROMO_CARD_WIDTH: 180,
  PROMO_CARD_GAP: 16,
  PROMO_DISCOUNT_BADGE_SIZE: 12,
  PROMO_PERCENT_BADGE_SIZE: 48,
  
  // Product Section
  SECTION_PADDING: 16,
  SECTION_TITLE_SIZE: 20,
  PRODUCT_ITEM_HEIGHT: 120,
  PRODUCT_IMAGE_SIZE: 96,
  PRODUCT_NAME_SIZE: 16,
  PRODUCT_PRICE_SIZE: 18,
  ADD_BUTTON_SIZE: 38,
} as const;