export const ORDER_DETAIL_STRINGS = {
  TITLE: 'Chi tiết đơn hàng',
  LOADING: 'Đang tải...',
  ERROR_LOAD: 'Không thể tải chi tiết đơn hàng',
  RETRY: 'Thử lại',
  ORDER_INFO: 'Thông tin đơn hàng',
  ITEMS: 'Món đã đặt',
  SUMMARY: 'Tổng kết',
  SUBTOTAL: 'Tạm tính',
  DELIVERY_FEE: 'Phí giao hàng',
  DISCOUNT: 'Giảm giá',
  TOTAL: 'Tổng cộng',
  PAYMENT_METHOD: 'Phương thức thanh toán',
  PAYMENT_STATUS: 'Trạng thái thanh toán',
  ORDER_STATUS: 'Trạng thái đơn hàng',
  CREATED_AT: 'Thời gian đặt',
  NOTE: 'Ghi chú',
  CONTACT: 'Liên hệ',
  ADDRESS: 'Địa chỉ giao hàng',
  CASH: 'Tiền mặt',
  CARD: 'Thẻ',
  MOMO: 'MoMo',
  ZALOPAY: 'ZaloPay',
};

export const PAYMENT_METHOD_LABELS: Record<string, string> = {
  cash: ORDER_DETAIL_STRINGS.CASH,
  card: ORDER_DETAIL_STRINGS.CARD,
  momo: ORDER_DETAIL_STRINGS.MOMO,
  zalopay: ORDER_DETAIL_STRINGS.ZALOPAY,
};