export const MAP_LAYOUT = {
  // MapView
  MAP_HEIGHT: 300,
  MAP_BORDER_RADIUS: 12,
  
  // MapPicker
  PICKER_HEIGHT: 400,
  MARKER_SIZE: 40,
  CONFIRM_BUTTON_HEIGHT: 48,
  CONFIRM_BUTTON_MARGIN: 16,
  
  // AddressSearchModal
  MODAL_HEIGHT_PERCENTAGE: 0.8,
  SEARCH_INPUT_HEIGHT: 48,
  SEARCH_INPUT_PADDING: 16,
  SEARCH_INPUT_BORDER_RADIUS: 12,
  
  // Search Result Item
  RESULT_ITEM_PADDING: 16,
  RESULT_ITEM_GAP: 8,
  RESULT_ICON_SIZE: 20,
  RESULT_TITLE_FONT_SIZE: 16,
  RESULT_SUBTITLE_FONT_SIZE: 14,
  
  // DeliveryAddressCard
  CARD_PADDING: 16,
  CARD_BORDER_RADIUS: 12,
  CARD_GAP: 8,
  CARD_ICON_SIZE: 24,
  CARD_TITLE_FONT_SIZE: 16,
  CARD_ADDRESS_FONT_SIZE: 14,
  EDIT_BUTTON_SIZE: 32,
};