export const STORES_LAYOUT = {
  // Header
  HEADER_PADDING_HORIZONTAL: 16,
  HEADER_PADDING_VERTICAL: 16,
  HEADER_TITLE_SIZE: 20,
  HEADER_ICON_SIZE: 40,
  HEADER_ICON_BORDER_RADIUS: 20,
  HEADER_BADGE_SIZE: 20,
  HEADER_BADGE_FONT_SIZE: 12,
  HEADER_BADGE_TOP: -4,
  HEADER_BADGE_RIGHT: -4,
  
  // Search bar
  SEARCH_BAR_MARGIN_HORIZONTAL: 16,
  SEARCH_BAR_MARGIN_BOTTOM: 20,
  SEARCH_BAR_BORDER_RADIUS: 12,
  SEARCH_BAR_PADDING_HORIZONTAL: 16,
  SEARCH_BAR_PADDING_VERTICAL: 12,
  SEARCH_BAR_GAP: 10,
  SEARCH_INPUT_FONT_SIZE: 12,
  SEARCH_BAR_HEIGHT: 40,
  
  // Map button
  MAP_BUTTON_PADDING_HORIZONTAL: 10,
  MAP_BUTTON_PADDING_VERTICAL: 10,
  MAP_BUTTON_BORDER_RADIUS: 12,
  MAP_BUTTON_GAP: 8,
  MAP_BUTTON_FONT_SIZE: 12,
  
  // Section
  SECTION_MARGIN_HORIZONTAL: 16,
  SECTION_MARGIN_BOTTOM: 24,
  SECTION_TITLE_SIZE: 18,
  SECTION_TITLE_MARGIN_BOTTOM: 16,
  
  // Store card
  STORE_CARD_BORDER_RADIUS: 12,
  STORE_CARD_PADDING: 12,
  STORE_CARD_MARGIN_BOTTOM: 12,
  STORE_CARD_GAP: 12,
  STORE_IMAGE_SIZE: 80,
  STORE_IMAGE_BORDER_RADIUS: 8,
  STORE_BRAND_FONT_SIZE: 12,
  STORE_NAME_FONT_SIZE: 16,
  STORE_NAME_MARGIN_BOTTOM: 4,
  STORE_DISTANCE_FONT_SIZE: 14,
} as const;