export const OTP_LAYOUT = {
  // Modal
  MODAL_HEIGHT_PERCENTAGE: 0.9,
  MODAL_BORDER_RADIUS: 20,
  
  // Close button
  CLOSE_BUTTON_SIZE: 40,
  CLOSE_BUTTON_TOP: 16,
  CLOSE_BUTTON_RIGHT: 16,
  CLOSE_BUTTON_BORDER_RADIUS: 20,
  CLOSE_BUTTON_FONT_SIZE: 14,
  
  // Content padding
  CONTENT_PADDING_HORIZONTAL: 24,
  CONTENT_PADDING_TOP: 60,
  
  // Title
  TITLE_FONT_SIZE: 24,
  TITLE_MARGIN_BOTTOM: 16,
  
  // Subtitle
  SUBTITLE_FONT_SIZE: 14,
  SUBTITLE_LINE_HEIGHT: 20,
  SUBTITLE_MARGIN_BOTTOM: 32,
  
  // Input label
  INPUT_LABEL_FONT_SIZE: 14,
  INPUT_LABEL_MARGIN_BOTTOM: 24,
  
  // OTP Input boxes
  OTP_BOX_SIZE: 52,
  OTP_BOX_GAP: 12,
  OTP_BOX_BORDER_RADIUS: 12,
  OTP_BOX_BORDER_WIDTH: 2,
  OTP_BOX_FONT_SIZE: 24,
  
  // Timer section
  TIMER_MARGIN_TOP: 24,
  TIMER_FONT_SIZE: 14,
  TIMER_LINE_HEIGHT: 20,
  
  // Error section
  ERROR_MARGIN_TOP: 16,
  ERROR_FONT_SIZE: 14,
  ERROR_LINE_HEIGHT: 20,
  
  // Retry button
  RETRY_BUTTON_SIZE: 32,
  RETRY_BUTTON_MARGIN_LEFT: 8,
  
  // OK button
  OK_BUTTON_MARGIN_TOP: 24,
  OK_BUTTON_PADDING_VERTICAL: 14,
  OK_BUTTON_BORDER_RADIUS: 12,
  OK_BUTTON_FONT_SIZE: 16,
  
  // Animation
  SHAKE_AMPLITUDE: 10,
  SHAKE_DURATION: 500,
};