export const ADDRESS_MANAGEMENT_LAYOUT = {
  // Header
  HEADER_PADDING: 16,
  HEADER_TITLE_FONT_SIZE: 20,
  
  // List
  LIST_PADDING: 16,
  LIST_GAP: 12,
  
  // Address Item
  ITEM_PADDING: 16,
  ITEM_BORDER_RADIUS: 12,
  ITEM_GAP: 12,
  
  // Icon
  ICON_SIZE: 24,
  ICON_CONTAINER_SIZE: 48,
  
  // Badge
  BADGE_PADDING_HORIZONTAL: 8,
  BADGE_PADDING_VERTICAL: 4,
  BADGE_FONT_SIZE: 12,
  BADGE_BORDER_RADIUS: 6,
  
  // Button
  ADD_BUTTON_HEIGHT: 48,
  ADD_BUTTON_BORDER_RADIUS: 12,
  
  // Empty State
  EMPTY_ICON_SIZE: 80,
  EMPTY_MESSAGE_FONT_SIZE: 18,
  EMPTY_SUBTITLE_FONT_SIZE: 14,
  
  // Modal
  MODAL_PADDING: 20,
  MODAL_BORDER_RADIUS: 16,
  MODAL_INPUT_HEIGHT: 48,
  MODAL_BUTTON_HEIGHT: 48,
};