export const SEARCH_LAYOUT = {
  // Header
  HEADER_PADDING_HORIZONTAL: 16,
  HEADER_PADDING_VERTICAL: 12,
  HEADER_GAP: 12,
  HEADER_BORDER_BOTTOM_WIDTH: 2,
  
  // Search bar
  SEARCH_BAR_BORDER_RADIUS: 10,
  SEARCH_BAR_PADDING_HORIZONTAL: 16,
  SEARCH_BAR_GAP: 8,
  
  // List
  LIST_PADDING: 16,
  
  // Product item
  ITEM_BORDER_RADIUS: 12,
  ITEM_PADDING: 12,
  ITEM_MARGIN_BOTTOM: 12,
  ITEM_GAP: 12,
  
  // Product image
  IMAGE_SIZE: 80,
  IMAGE_BORDER_RADIUS: 8,
  
  // Badge
  BADGE_TOP: 4,
  BADGE_RIGHT: 4,
  BADGE_LEFT: 4,
  BADGE_BORDER_RADIUS: 8,
  BADGE_PADDING_HORIZONTAL: 6,
  BADGE_PADDING_VERTICAL: 2,
  
  // Add button
  ADD_BUTTON_SIZE: 36,
  ADD_BUTTON_BORDER_RADIUS: 18,
  
  // Font sizes
  SEARCH_INPUT_FONT_SIZE: 12,
  CANCEL_BUTTON_FONT_SIZE: 12,
  SEARCH_ICON_FONT_SIZE: 14,
  IMAGE_PLACEHOLDER_FONT_SIZE: 12,
  BADGE_FONT_SIZE: 9,
  PRODUCT_NAME_FONT_SIZE: 14,
  PRODUCT_PRICE_FONT_SIZE: 16,
  ADD_ICON_FONT_SIZE: 24,
  
  // Debounce timing
  SEARCH_DEBOUNCE_MS: 300,
};