// src/presentation/screens/deals/DealsLayout.ts
export const DEALS_LAYOUT = {
  // Login card
  LOGIN_CARD_MARGIN_HORIZONTAL: 16,
  LOGIN_CARD_MARGIN_TOP: 16,
  LOGIN_CARD_MARGIN_BOTTOM: 32,
  LOGIN_CARD_BORDER_RADIUS: 20,
  LOGIN_CARD_PADDING: 32,
  LOGIN_CARD_MIN_HEIGHT: 200,
  LOGIN_BUTTON_BORDER_RADIUS: 24,
  LOGIN_BUTTON_PADDING_VERTICAL: 14,
  LOGIN_TEXT_SIZE: 16,
  LOGIN_BUTTON_SIZE: 16,

  // Tier section
  TIER_SECTION_MARGIN_BOTTOM: 24,
  TIER_SECTION_PADDING_HORIZONTAL: 16,
  TIER_TITLE_SIZE: 24,
  TIER_TITLE_MARGIN_BOTTOM: 4,
  TIER_SUBTITLE_SIZE: 16,
  TIER_SUBTITLE_MARGIN_BOTTOM: 20,
  TIER_SECTION_PADDING_TOP: 16,
  TIER_SECTION_PADDING_BOTTOM: 16,

  // Tier cards
  TIER_CONTAINER_PADDING_VERTICAL: 12,
  TIER_CONTAINER_PADDING_HORIZONTAL: 8,
  TIER_CARD_WIDTH: 55,
  TIER_CARD_HEIGHT: 40,
  TIER_CARD_BORDER_RADIUS: 8,
  TIER_LOGO_SIZE: 12,
  TIER_NAME_SIZE: 12,
  TIER_NAME_MARGIN_TOP: 12,
  TIER_NAME_MARGIN_BOTTOM: 4,

  // Benefits list
  BENEFITS_PADDING_HORIZONTAL: 16,
  BENEFIT_ITEM_PADDING_VERTICAL: 16,
  BENEFIT_ICON_SIZE: 48,
  BENEFIT_GAP: 12,
  BENEFIT_TEXT_SIZE: 12,
  BENEFIT_BORDER_WIDTH: 1,
} as const;