export const REGISTER_LAYOUT = {
  // Hero section
  HERO_HEIGHT: 280,

  // Close button
  CLOSE_BUTTON_SIZE: 40,
  CLOSE_BUTTON_TOP: 16,
  CLOSE_BUTTON_RIGHT: 16,
  CLOSE_BUTTON_BORDER_RADIUS: 20,

  // Form container
  FORM_PADDING_HORIZONTAL: 24,
  FORM_PADDING_TOP: 32,

  // Input
  INPUT_BORDER_RADIUS: 12,
  INPUT_PADDING_HORIZONTAL: 16,
  INPUT_PADDING_VERTICAL: 14,
  INPUT_GAP: 12,
  INPUT_BORDER_WIDTH: 1,

  // Button
  BUTTON_BORDER_RADIUS: 12,
  BUTTON_PADDING_VERTICAL: 16,

  // Font sizes
  CLOSE_BUTTON_FONT_SIZE: 14,
  HERO_FONT_SIZE: 16,
  WELCOME_FONT_SIZE: 16,
  BRAND_NAME_FONT_SIZE: 28,
  INPUT_FONT_SIZE: 16,
  BUTTON_FONT_SIZE: 16,
  LINK_FONT_SIZE: 14,

  // Spacing
  WELCOME_MARGIN_BOTTOM: 8,
  BRAND_NAME_MARGIN_BOTTOM: 32,
  INPUT_MARGIN_BOTTOM: 24,
  LINK_MARGIN_TOP: 24,

  // Timing
  KEYBOARD_FOCUS_DELAY: 400,
  OTP_SENDING_DURATION: 500,
};