export const HOME_LAYOUT = {
  // Header
  HEADER_PADDING_HORIZONTAL: 16,
  HEADER_PADDING_VERTICAL: 12,
  HEADER_BORDER_BOTTOM_WIDTH: 1,
  HEADER_ICON_SIZE: 40,
  HEADER_ICON_BORDER_RADIUS: 20,
  GREETING_ICON_SIZE: 24,
  GREETING_TEXT_SIZE: 16,
  GREETING_GAP: 8,
  VOUCHER_BADGE_PADDING_HORIZONTAL: 12,
  VOUCHER_BADGE_PADDING_VERTICAL: 8,
  VOUCHER_BADGE_BORDER_RADIUS: 20,
  VOUCHER_BADGE_FONT_SIZE: 14,
  VOUCHER_BADGE_GAP: 4,
  NOTIFICATION_BADGE_SIZE: 18,
  NOTIFICATION_BADGE_FONT_SIZE: 10,
  NOTIFICATION_BADGE_TOP: -2,
  NOTIFICATION_BADGE_RIGHT: -2,

  // Section
  SECTION_PADDING_HORIZONTAL: 16,
  SECTION_MARGIN_BOTTOM: 24,
  SECTION_TITLE_SIZE: 20,
  SECTION_TITLE_MARGIN_BOTTOM: 16,

  // Brand Selector (Home)
  HOME_BRAND_CARD_SIZE: 80,
  HOME_BRAND_CARD_BORDER_RADIUS: 12,
  HOME_BRAND_SCROLL_GAP: 12,
  HOME_BRAND_TEXT_SIZE: 14,
  HOME_BRAND_CARD_PADDING: 16,
  HOME_BRAND_CARD_MARGIN_BOTTOM: 5,
  HOME_BRAND_CARD_MARGIN_LEFT: 5,

  // Quick Actions (Home)
  HOME_QUICK_ACTION_ICON_SIZE: 60,
  HOME_QUICK_ACTION_ICON_BORDER_RADIUS: 30,
  HOME_QUICK_ACTION_GAP: 8,
  HOME_QUICK_ACTION_LABEL_SIZE: 12,
  HOME_QUICK_ACTION_CONTAINER_BORDER_RADIUS: 16,
  HOME_QUICK_ACTION_CONTAINER_PADDING: 16,

  // Search Bar (Home)
  HOME_SEARCH_BAR_BORDER_RADIUS: 24,
  HOME_SEARCH_BAR_PADDING_HORIZONTAL: 16,
  HOME_SEARCH_BAR_PADDING_VERTICAL: 12,
  HOME_SEARCH_BAR_GAP: 8,
  HOME_SEARCH_BAR_FONT_SIZE: 14,

  // Category Scroll (Home)
  HOME_CATEGORY_ITEM_WIDTH: 80,
  HOME_CATEGORY_ICON_SIZE: 60,
  HOME_CATEGORY_ICON_BORDER_RADIUS: 30,
  HOME_CATEGORY_ICON_MARGIN_BOTTOM: 8,
  HOME_CATEGORY_SCROLL_GAP: 16,
  HOME_CATEGORY_LABEL_SIZE: 11,

  // Combo Hot Sale - Section Container (NO white card wrapper)
  COMBO_SECTION_MARGIN_BOTTOM: 32,
  COMBO_SECTION_PADDING_HORIZONTAL: 16,

  // Combo Hot Sale - Title & Countdown (OUTSIDE scroll)
  COMBO_TITLE_FONT_SIZE: 24,
  COMBO_TITLE_MARGIN_BOTTOM: 8,
  COMBO_TITLE_LINE_HEIGHT: 32,
  COMBO_COUNTDOWN_CONTAINER_MARGIN_BOTTOM: 16,
  COMBO_COUNTDOWN_LABEL_FONT_SIZE: 14,
  COMBO_COUNTDOWN_VALUE_FONT_SIZE: 16,
  COMBO_COUNTDOWN_GAP: 8,

  // Combo Hot Sale - Product Scroll
  COMBO_PRODUCT_SCROLL_GAP: 16,
  COMBO_PRODUCT_SCROLL_PADDING_VERTICAL: 8,

  // Combo Hot Sale - Product Card (similar to ProductCard)
  COMBO_PRODUCT_CARD_WIDTH: 180,
  COMBO_PRODUCT_CARD_BORDER_RADIUS: 12,
  COMBO_PRODUCT_CARD_MARGIN_BOTTOM: 16,
  COMBO_PRODUCT_IMAGE_ASPECT_RATIO: 1,
  COMBO_PRODUCT_IMAGE_BORDER_RADIUS_TOP_LEFT: 12,
  COMBO_PRODUCT_IMAGE_BORDER_RADIUS_TOP_RIGHT: 12,

  // Combo Hot Sale - Product Info
  COMBO_PRODUCT_INFO_PADDING: 12,
  COMBO_PRODUCT_NAME_FONT_SIZE: 14,
  COMBO_PRODUCT_NAME_MARGIN_BOTTOM: 8,
  COMBO_PRODUCT_NAME_MIN_HEIGHT: 40,
  COMBO_PRODUCT_PRICE_FONT_SIZE: 16,
  COMBO_PRODUCT_PRICE_MARGIN_BOTTOM: 12,

  // Combo Hot Sale - Discount Badge (red rectangle)
  COMBO_DISCOUNT_BADGE_TOP: 8,
  COMBO_DISCOUNT_BADGE_LEFT: 8,
  COMBO_DISCOUNT_BADGE_BORDER_RADIUS: 8,
  COMBO_DISCOUNT_BADGE_PADDING_HORIZONTAL: 8,
  COMBO_DISCOUNT_BADGE_PADDING_VERTICAL: 4,
  COMBO_DISCOUNT_BADGE_FONT_SIZE: 12,

  // Combo Hot Sale - Best Seller Badge (if needed later)
  COMBO_BEST_SELLER_BADGE_TOP: 8,
  COMBO_BEST_SELLER_BADGE_RIGHT: 8,
  COMBO_BEST_SELLER_BADGE_SIZE: 48,

  // Combo Hot Sale - Choose Button
  COMBO_PRODUCT_BUTTON_BORDER_RADIUS: 24,
  COMBO_PRODUCT_BUTTON_PADDING_VERTICAL: 12,
  COMBO_PRODUCT_BUTTON_FONT_SIZE: 16,

  // Collection
  COLLECTION_CARD_WIDTH: 280,
  COLLECTION_CARD_HEIGHT: 160,
  COLLECTION_CARD_BORDER_RADIUS: 16,
  COLLECTION_SCROLL_GAP: 16,
  COLLECTION_TITLE_FONT_SIZE: 18,
  COLLECTION_DESC_FONT_SIZE: 14,
  COLLECTION_MODAL_HEIGHT_PERCENTAGE: 0.95,
  COLLECTION_OVERLAY_PADDING: 12,
  COLLECTION_OVERLAY_TITLE_MARGIN_BOTTOM: 4,

  // Auto-swipe promo
  PROMO_AUTO_SWIPE_INTERVAL: 3000,
  PROMO_RESUME_DELAY: 3000,
  
  // Pagination dots (INSIDE banner)
  PROMO_DOT_HEIGHT: 1,
  PROMO_DOT_INACTIVE_WIDTH: 16,
  PROMO_DOT_ACTIVE_WIDTH: 16,
  PROMO_DOT_BORDER_RADIUS: 0.5,
  PROMO_DOT_GAP: 8,
  PROMO_DOT_BOTTOM: 5,
  PROMO_DOT_CONTAINER_PADDING_HORIZONTAL: 16,
} as const;